# Generated by Django 5.0.2 on 2024-02-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('quantity', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
